title: My blog
email: redsharpobject@gmail.com
description: "Gaming, modding, programming"
url: "https://redsharpobject.github.com"
github_username: RedSharpObject

plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed
