title: My blog
email: redsharpobject@gmail.com
description: "Gaming, modding, programming"
url: "https://redsharpobject.github.com"
github_username: RedSharpObject

plugins:
  - jekyll-feed

exclude:
  - README.md
