title: RedSharpObject's official website
email: redsharpobject@gmail.com
description: "Game development and programming."
url: "https://redsharpobject.github.com"
github_username: RedSharpObject

exclude:
  - README.md
  - license